server:
  port: 8082 # Ensure this port is different from others

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5433/productdb
    username: yourUsername
    password: yourPassword
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
