spring.application.name=product-service
spring.datasource.url=jdbc:postgresql://localhost:5433/productdb
spring.datasource.username=yourUsername
spring.datasource.password=yourPassword

spring.jpa.hibernate.ddl-auto=update


eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true